/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 car.gltf 
Author: oakar258 (https://sketchfab.com/oakar258)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hcr2-racing-truck-8506b2861e734c4083db2e96a717dbf1
Title: HCR2 Racing Truck
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/car.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.799, 1.598, 0.658]}>
        <mesh geometry={nodes.Object_22.geometry} material={materials.RT_main} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Glass} />
      </group>
      <group position={[0.799, 1.598, 0.658]}>
        <mesh geometry={nodes.Object_25.geometry} material={materials.RT_main} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Glass} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.RT_Wheel} position={[0.899, 0.611, -1.852]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.RT_Wheel} position={[0.807, 0.518, 1.62]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.RT_Wheel} position={[-0.899, 0.611, -1.852]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.RT_Wheel} position={[-0.807, 0.518, 1.62]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.RT_main} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.RT_main} position={[0.395, 1.687, 0.602]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.RT_main} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.RT_main} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.RT_main} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.RT_main} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.RT_main} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.RT_main} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.RT_main} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.RT_main} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.RT_main} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.RT_main} />
    </group>
  )
}

useGLTF.preload('/car.gltf')
